import { useState } from "react";
const C={bg:"#080a06",panel:"#0e100c",border:"#1e2818",amber:"#d97706",gold:"#fbbf24",green:"#4ade80",cyan:"#22d3ee",red:"#f87171",purple:"#c084fc",blue:"#60a5fa",orange:"#fb923c",dim:"#4a5a3a",dimmer:"#1e2818",text:"#d4e0c8",textDim:"#7a8a6a",textBright:"#f0f4e8"};
const F={fontFamily:"'Courier New','Lucida Console',monospace"};
const TIPS=[
  {icon:"📦",title:"Extract Early — Gear is Everything",color:C.gold,body:"Most beginner deaths happen within 100 meters of extraction because players hesitate or keep looting. If your inventory is valuable, extract. One extra chest is not worth losing everything. The risk-reward loop is the entire game — discipline beats greed every run.",tip:"If you're debating whether to extract, extract. The feeling of losing a loaded inventory is brutal and avoidable."},
  {icon:"🔊",title:"Sound is Your Most Powerful Tool",color:C.green,body:"Footsteps, distant gunfire, doors opening, weapon swapping, healing sounds — all of it is directional and loud to nearby players. Crouch-walk near extraction points and after engagements. Repositioning after every fight is essential — gunshots broadcast your position.",tip:"Crouching reduces your sound footprint significantly. Never sprint near extraction. Reposition immediately after every kill."},
  {icon:"🌡️",title:"Heat = Your Stamina Bar — Manage It",color:C.orange,body:"Heat is generated by sprinting, using abilities, and certain weapons. If you overheat you're slowed and vulnerable. Crouch to cool down fast. Water and rain also reduce heat. Manage heat actively.",tip:"Crouching is the fastest heat cooldown. Find shade, water, or rain for passive cooling mid-fight."},
  {icon:"👥",title:"DBNO — Teammates Can Revive You",color:C.cyan,body:"When you take lethal damage you go Down But Not Out (DBNO) — teammates have a window to revive you. Don't give up immediately. Communicate your position.",tip:"Give teammates 5–10 seconds before giving up in DBNO. A revive is free. Respawning costs gear."},
  {icon:"🔫",title:"Master 2–3 Weapons — Don't Chase Everything",color:C.gold,body:"Marathon has 28+ weapons. New players who constantly switch never develop the muscle memory that wins fights. Pick 2–3 weapons you're comfortable with and master their recoil, TTK, and reload timing.",tip:"In your first 10 hours, pick one primary, one backup, and stick to them."},
  {icon:"🆕",title:"Rook Mode for Learning — No Gear Loss",color:C.green,body:"Rook is a specialized scavenger frame with no starting gear and nothing to lose. You drop into in-progress crew lobbies. Perfect low-pressure way to learn map layouts, extraction routes, and engagement timing.",tip:"Play 10+ Rook sessions before investing in a real loadout. Learn the maps and extraction windows first."},
  {icon:"🗺️",title:"Learn Extraction Routes Before Loot Routes",color:C.amber,body:"Know where every extraction pylon is before you worry about loot locations. Extraction requires activating a pylon and surviving the warm-up window — the noise and location alert nearby squads.",tip:"In new maps, ignore loot your first few runs. Just find all extraction pylons and memorize their locations."},
  {icon:"⚡",title:"The TTK is Short — Positioning Wins Fights",color:C.red,body:"Time-to-kill in Marathon is fast. Wide open engagements favor whoever shoots first. Use cover constantly. Third-partying is one of the strongest strategies — let two squads weaken each other, then push.",tip:"Third-party every fight you can afford to. Two weakened squads are easier to finish than one full-health squad."},
  {icon:"🏆",title:"Factions — Pick One and Focus Early",color:C.purple,body:"Six factions each have unique contracts, upgrades, and rewards. Spreading attention across all of them early slows progression significantly. Pick one faction that matches your playstyle and complete their contracts consistently.",tip:"CyberAcme and MIDA are the most beginner-friendly factions. Pick one and grind their contracts for the first season."},
  {icon:"🔧",title:"Implants and Cores — Your Actual Build",color:C.cyan,body:"Your Runner Shell is just the foundation. Implants (head, torso, legs, shield) and Cores define your build. Up to 4 weapon mods per gun with 8 attachment slots. Build around your Shell's strengths.",tip:"Read every implant description before equipping. Some Prestige Unique Traits are build-defining."},
  {icon:"📍",title:"Contracts — How You Progress",color:C.gold,body:"Contracts are your weekly pool of objectives tied to your faction. Completing them raises faction reputation, unlocks upgrades, and gives powerful loot. Route your runs around active contracts.",tip:"Check your active contracts before dropping. Route your run around objectives — never waste a run ignoring available contract progress."},
];
const RUNNERS=[
  {name:"Destroyer",role:"Tank",tier:"A",color:C.red,solo:"B",squad:"S",prime:"Missile barrage — launches multiple homing missiles at targets",tactical:"Riot Barricade — deployable shield that blocks projectiles",traits:"Armor passive, damage resistance when stationary",best:"Front-line brawler, holds chokepoints, squad anchor",tip:"Destroyer excels at controlling extraction areas. Deploy Riot Barricade at the pylon and hold the line."},
  {name:"Vandal",role:"Aggressive Flanker",tier:"S",color:C.orange,solo:"A",squad:"A",prime:"Double jump — activate in air for a second jump (generates heat)",tactical:"Supercharged slide — fast directional movement with extra heat cost",traits:"Movement speed bonuses, weapon dexterity",best:"Aggressive flanking, fast rotations, surprise engagements",tip:"If you played Apex's Octane, Vandal will feel familiar. Master heat management or you'll be defenseless mid-fight."},
  {name:"Recon",role:"Intel / Support",tier:"A",color:C.cyan,solo:"C",squad:"S",prime:"Sonar pulse — releases pulses that reveal nearby hostile locations",tactical:"Tracker bot — microbot that hunts hostiles and overheats them on explosion",traits:"Detection awareness, tracking uptime bonuses",best:"Squad play — information advantage is priceless in coordinated teams",tip:"Recon solo is tough but Recon in a coordinated squad is oppressive. Call out everything your sonar reveals."},
  {name:"Assassin",role:"Stealth Ambush",tier:"B",color:C.purple,solo:"A",squad:"B",prime:"Cloaking — temporary invisibility",tactical:"Sensor disruption — scrambles enemy detection systems",traits:"Stealth movement bonuses, reduced heat while cloaked",best:"Solo play, picking off separated targets, avoiding third parties",tip:"Assassin rewards patience. Don't use the cloak aggressively — use it to disengage and reposition after kills."},
  {name:"Triage",role:"Support / Medic",tier:"B",color:C.green,solo:"C",squad:"A",prime:"Revive boost — enhanced teammate revival speed and range",tactical:"Healing station — deployable that heals nearby teammates",traits:"Passive healing bonuses, reduced revive time",best:"Dedicated squad support — requires coordinated teammates",tip:"Triage is only as good as your squad's communication. Solo queue Triage is one of the weakest picks."},
  {name:"Thief",role:"Looter / Scavenger",tier:"A",color:C.gold,solo:"S",squad:"B",prime:"Vault breach — bypasses locks and containers faster",tactical:"Loot scan — reveals nearby container and loot locations",traits:"Carry capacity bonuses, faster looting speed",best:"Solo play, high-value loot runs, quick extraction routes",tip:"Thief is arguably the best solo shell. More loot, faster looting, and a radar for valuable containers."},
  {name:"Rook",role:"Beginner Scavenger",tier:"N/A",color:C.dim,solo:"N/A",squad:"N/A",prime:"No abilities — drops into active lobbies with no gear",tactical:"N/A",traits:"No traits — the learning shell",best:"Learning maps, extraction routes, and combat without gear loss risk",tip:"Play this extensively before investing in a real shell. Losing a Rook run costs nothing."},
];
const MAPS=[
  {name:"Perimeter",difficulty:"Beginner",color:C.green,desc:"The starting map. Dense urban ruins with tight corridors and clear sightlines. Multiple extraction points. Lower player density and easier AI. Best map to learn extraction timing.",tip:"Learn every extraction pylon location here before moving to harder maps."},
  {name:"Dire Marsh",difficulty:"Intermediate",color:C.amber,desc:"Vast open marshland with limited visibility from fog and vegetation. Long sightlines in clearings make open engagements dangerous. AI patrols are more aggressive. Higher loot density.",tip:"Stick to the treeline and vegetation. Never cross open clearings without knowing where other squads are."},
  {name:"Outpost",difficulty:"Advanced",color:C.red,desc:"Former spaceport full of vertical structures and secrets. Unlocks at Runner Level 12. High loot density, more dangerous AI, and aggressive player presence. Multiple elevation levels.",tip:"Don't enter Outpost until you're comfortable with extraction timing and TTK. It will punish underprepared runners."},
  {name:"Cryo Archive",difficulty:"Endgame",color:C.purple,desc:"The first deck of the UESC Marathon ship in orbit. Raid-like security measures, frozen vaults, and a boss entity in Vault 7. Fully-geared enemy crews racing for the same prizes.",tip:"Don't enter Cryo Archive without a coordinated squad and full endgame loadout. This is not a casual loot zone."},
];
const WEAPONS_TIERS=[
  {tier:"S",color:C.gold,weapons:[{name:"WSTR Combat Shotgun",type:"Shotgun",note:"Best close-quarters weapon. Devastating TTK at range it's designed for."},{name:"M77 Assault Rifle (Modified)",type:"AR",note:"Fast fire, deep mag. Reliable at mid-range with good mod slots."},{name:"V00 Zeus Rail Gun",type:"Sniper",note:"Long-range dominant. One-shot kill potential. High-risk high-reward."}]},
  {tier:"A",color:C.cyan,weapons:[{name:"Outland",type:"AR",note:"Solid mid-range control. Good balance of damage, recoil, and mag size."},{name:"SMG (standard)",type:"SMG",note:"Exceptional close to mid-range. High fire rate, manageable recoil."},{name:"Volt weapons",type:"Energy",note:"Energy ammo type. Strong against shields specifically."}]},
  {tier:"B",color:C.amber,weapons:[{name:"MIPS weapons",type:"Exotic",note:"Strange hybrid human/alien tech. High ceiling but requires mastery."},{name:"Standard Pistol",type:"Pistol",note:"Reliable backup. Consistent TTK for a sidearm."},{name:"Hybrid Rifles",type:"AR",note:"Mid-range options. Situationally strong depending on mods."}]},
  {tier:"C",color:C.dim,weapons:[{name:"Light Ammo weapons (base)",type:"Various",note:"Functional early on but fall off fast. Replace as soon as possible."}]},
];
const TABS=["TIPS","RUNNERS","MAPS","WEAPONS"];
const TAB_COLORS={TIPS:C.gold,RUNNERS:C.amber,MAPS:C.green,WEAPONS:C.cyan};
export default function MarathonGuide(){
  const[tab,setTab]=useState("TIPS");
  const[expanded,setExpanded]=useState(null);
  const[search,setSearch]=useState("");
  const f=(s)=>s.toLowerCase().includes(search.toLowerCase());
  return(
    <div style={{...F,background:C.bg,minHeight:"100vh",color:C.text}}>
      <div style={{position:"fixed",inset:0,backgroundImage:"repeating-linear-gradient(0deg,transparent,transparent 3px,rgba(217,119,6,0.006) 3px,rgba(217,119,6,0.006) 6px)",pointerEvents:"none",zIndex:0}}/>
      <div style={{position:"relative",zIndex:1,maxWidth:960,margin:"0 auto",padding:"20px 16px"}}>
        <div style={{textAlign:"center",marginBottom:22}}>
          <div style={{display:"inline-block",border:`1px solid ${C.amber}44`,borderTop:`2px solid ${C.amber}`,padding:"3px 18px",marginBottom:6}}>
            <span style={{fontSize:10,letterSpacing:5,color:`${C.amber}88`}}>BUNGIE · PS5 / PC / XBOX · MAR 5 2026</span>
          </div>
          <h1 style={{fontSize:22,fontWeight:900,letterSpacing:3,margin:"5px 0 3px",color:C.textBright,textTransform:"uppercase"}}>MARATHON</h1>
          <p style={{fontSize:11,color:C.textDim,letterSpacing:2,margin:0}}>FIELD GUIDE · PvPvE EXTRACTION SHOOTER · TAU CETI IV</p>
        </div>
        <div style={{display:"flex",gap:3,marginBottom:16,flexWrap:"wrap"}}>
          {TABS.map(t=>{const col=TAB_COLORS[t];const active=tab===t;return<button key={t} onClick={()=>{setTab(t);setExpanded(null);setSearch("");}} style={{flex:"1 1 auto",padding:"10px 6px",background:active?`${col}12`:C.panel,border:active?`1px solid ${col}`:`1px solid ${C.border}`,borderTop:active?`2px solid ${col}`:"2px solid transparent",color:active?col:C.dim,cursor:"pointer",fontSize:12,letterSpacing:3,...F,fontWeight:active?700:400,whiteSpace:"nowrap"}}>{t}</button>;})}
        </div>
        <div style={{marginBottom:14,position:"relative"}}>
          <span style={{position:"absolute",left:10,top:"50%",transform:"translateY(-50%)",color:`${C.amber}44`,fontSize:13}}>⌕</span>
          <input value={search} onChange={e=>{setSearch(e.target.value);setExpanded(null);}} placeholder={`SEARCH ${tab}...`} style={{width:"100%",boxSizing:"border-box",background:"#0a0c08",border:`1px solid ${C.border}`,borderLeft:`2px solid ${C.amber}44`,color:"#d4c898",padding:"9px 10px 9px 28px",fontSize:11,letterSpacing:1,outline:"none",...F}}/>
        </div>
        {tab==="TIPS"&&(<>
          <div style={{fontSize:12,color:C.textDim,letterSpacing:2,marginBottom:14}}>CORE RULES · EXTRACT ALIVE · DISCIPLINE OVER GREED</div>
          {TIPS.filter(s=>!search||f(s.title)||f(s.body)).map((s,i)=>{const open=expanded===`t-${i}`;return(
            <div key={i} style={{border:`1px solid ${open?s.color+"55":C.border}`,marginBottom:8,background:C.panel}}>
              <div onClick={()=>setExpanded(open?null:`t-${i}`)} style={{padding:"12px 14px",cursor:"pointer",display:"flex",justifyContent:"space-between",alignItems:"center",gap:8,background:open?`${s.color}08`:"transparent",borderBottom:open?`1px solid ${C.border}`:"none"}} onMouseEnter={e=>e.currentTarget.style.background=`${s.color}0a`} onMouseLeave={e=>e.currentTarget.style.background=open?`${s.color}08`:"transparent"}>
                <div style={{display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:18}}>{s.icon}</span><span style={{fontSize:14,color:C.textBright,fontWeight:700}}>{s.title}</span></div>
                <span style={{color:s.color,fontSize:14,flexShrink:0}}>{open?"▲":"▼"}</span>
              </div>
              {open&&(<div style={{padding:"12px 14px"}}><div style={{fontSize:13,color:C.text,lineHeight:1.8,marginBottom:10}}>{s.body}</div><div style={{background:`${s.color}08`,padding:"8px 12px",borderLeft:`2px solid ${s.color}66`,fontSize:12,color:s.color,lineHeight:1.6}}>⚡ {s.tip}</div></div>)}
            </div>
          );})}
        </>)}
        {tab==="RUNNERS"&&(<>
          <div style={{fontSize:12,color:C.textDim,letterSpacing:2,marginBottom:14}}>7 RUNNER SHELLS · SWAP FREELY OUTSIDE RAIDS · ROOK IS THE LEARNING SHELL</div>
          {RUNNERS.filter(r=>!search||f(r.name)||f(r.role)||f(r.best)).map((r,i)=>{const open=expanded===`r-${i}`;return(
            <div key={i} style={{border:`1px solid ${open?r.color+"55":C.border}`,marginBottom:8,background:C.panel}}>
              <div onClick={()=>setExpanded(open?null:`r-${i}`)} style={{padding:"12px 14px",cursor:"pointer",display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:8,background:open?`${r.color}08`:"transparent",borderBottom:open?`1px solid ${C.border}`:"none"}} onMouseEnter={e=>e.currentTarget.style.background=`${r.color}0a`} onMouseLeave={e=>e.currentTarget.style.background=open?`${r.color}08`:"transparent"}>
                <div style={{flex:1}}>
                  <div style={{display:"flex",alignItems:"center",gap:8,flexWrap:"wrap",marginBottom:4}}>
                    <span style={{fontSize:14,color:C.textBright,fontWeight:700}}>{r.name}</span>
                    <span style={{fontSize:10,color:r.color,background:`${r.color}15`,border:`1px solid ${r.color}44`,padding:"2px 7px",letterSpacing:1}}>{r.role.toUpperCase()}</span>
                    {r.tier!=="N/A"&&<span style={{fontSize:12,color:r.color,fontWeight:900}}>{r.tier}-TIER</span>}
                  </div>
                  <div style={{display:"flex",gap:12,flexWrap:"wrap"}}>
                    <span style={{fontSize:11,color:C.textDim}}>Solo: <span style={{color:r.solo==="S"?C.gold:r.solo==="A"?C.green:r.solo==="B"?C.amber:C.dim}}>{r.solo}</span></span>
                    <span style={{fontSize:11,color:C.textDim}}>Squad: <span style={{color:r.squad==="S"?C.gold:r.squad==="A"?C.green:r.squad==="B"?C.amber:C.dim}}>{r.squad}</span></span>
                  </div>
                </div>
                <span style={{color:r.color,fontSize:14,flexShrink:0,marginTop:2}}>{open?"▲":"▼"}</span>
              </div>
              {open&&(<div style={{padding:"12px 14px"}}>
                <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:10}}>
                  <div style={{background:`${r.color}08`,padding:"8px 10px",borderLeft:`2px solid ${r.color}44`}}><div style={{fontSize:10,letterSpacing:2,color:r.color,marginBottom:4}}>PRIME ABILITY</div><div style={{fontSize:12,color:C.text,lineHeight:1.6}}>{r.prime}</div></div>
                  <div style={{background:`${r.color}08`,padding:"8px 10px",borderLeft:`2px solid ${r.color}44`}}><div style={{fontSize:10,letterSpacing:2,color:r.color,marginBottom:4}}>TACTICAL</div><div style={{fontSize:12,color:C.text,lineHeight:1.6}}>{r.tactical}</div></div>
                </div>
                <div style={{marginBottom:8,background:`${C.cyan}06`,padding:"8px 10px",borderLeft:`2px solid ${C.cyan}33`}}><div style={{fontSize:10,letterSpacing:2,color:C.cyan,marginBottom:4}}>TRAITS</div><div style={{fontSize:12,color:C.textDim,lineHeight:1.6}}>{r.traits}</div></div>
                <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}>
                  <div style={{background:`${C.gold}08`,padding:"8px 10px",borderLeft:`2px solid ${C.gold}44`}}><div style={{fontSize:10,letterSpacing:2,color:C.gold,marginBottom:4}}>BEST FOR</div><div style={{fontSize:12,color:C.textDim,lineHeight:1.6}}>{r.best}</div></div>
                  <div style={{background:`${r.color}08`,padding:"8px 10px",borderLeft:`2px solid ${r.color}44`}}><div style={{fontSize:10,letterSpacing:2,color:r.color,marginBottom:4}}>⚡ TIP</div><div style={{fontSize:12,color:C.textDim,lineHeight:1.6}}>{r.tip}</div></div>
                </div>
              </div>)}
            </div>
          );})}
        </>)}
        {tab==="MAPS"&&(<>
          <div style={{fontSize:12,color:C.textDim,letterSpacing:2,marginBottom:14}}>4 MAPS · START ON PERIMETER · OUTPOST UNLOCKS AT RUNNER LEVEL 12</div>
          <div style={{display:"flex",flexDirection:"column",gap:10,marginBottom:20}}>
            {MAPS.filter(m=>!search||f(m.name)||f(m.desc)).map((m,i)=>(
              <div key={i} style={{background:C.panel,border:`1px solid ${C.border}`,borderLeft:`3px solid ${m.color}`,padding:"14px 16px"}}>
                <div style={{display:"flex",alignItems:"center",gap:10,marginBottom:8,flexWrap:"wrap"}}>
                  <span style={{fontSize:15,color:C.textBright,fontWeight:700}}>{m.name}</span>
                  <span style={{fontSize:10,letterSpacing:2,color:m.color,background:`${m.color}15`,border:`1px solid ${m.color}44`,padding:"2px 8px"}}>{m.difficulty.toUpperCase()}</span>
                </div>
                <div style={{fontSize:13,color:C.textDim,lineHeight:1.7,marginBottom:8}}>{m.desc}</div>
                <div style={{background:`${m.color}08`,padding:"7px 10px",borderLeft:`2px solid ${m.color}44`,fontSize:12,color:m.color,lineHeight:1.5}}>⚡ {m.tip}</div>
              </div>
            ))}
          </div>
          <div style={{background:C.panel,border:`1px solid ${C.gold}44`,borderLeft:`3px solid ${C.gold}`,padding:"14px 16px"}}>
            <div style={{fontSize:12,letterSpacing:3,color:C.gold,marginBottom:10}}>HOW EXTRACTION WORKS</div>
            {["Find an extraction pylon on the map — marked by a signal icon","Activate the pylon — starts the extraction warm-up timer","The warm-up broadcasts your location with noise and light — nearby squads will converge","Survive the countdown window — then extract","If you die during the window, you lose all gear brought into the raid","Cryo Archive extraction is more complex — requires solving raid-like security measures"].map((step,i)=>(
              <div key={i} style={{display:"flex",gap:10,marginBottom:i<5?8:0}}>
                <span style={{color:C.gold,fontWeight:700,flexShrink:0,fontSize:12}}>{i+1}.</span>
                <span style={{fontSize:12,color:C.text,lineHeight:1.6}}>{step}</span>
              </div>
            ))}
          </div>
        </>)}
        {tab==="WEAPONS"&&(<>
          <div style={{fontSize:12,color:C.textDim,letterSpacing:2,marginBottom:14}}>28 WEAPONS · 4 AMMO TYPES (LIGHT / HEAVY / VOLT / MIPS) · 8 MOD SLOTS PER GUN</div>
          {WEAPONS_TIERS.map((tier,ti)=>{
            const filtered=tier.weapons.filter(w=>!search||f(w.name)||f(w.note)||f(w.type));
            if(!filtered.length)return null;
            return(<div key={ti} style={{marginBottom:18}}>
              <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}>
                <span style={{fontSize:16,fontWeight:900,color:tier.color}}>{tier.tier}</span>
                <div style={{width:2,height:16,background:tier.color}}/>
                <span style={{fontSize:10,letterSpacing:3,color:tier.color}}>TIER</span>
                <div style={{flex:1,height:1,background:`${tier.color}22`}}/>
              </div>
              <div style={{border:`1px solid ${C.border}`}}>
                <div style={{display:"grid",gridTemplateColumns:"1fr 90px 1fr",background:"#0c100a",borderBottom:`1px solid ${C.border}`}}>
                  {["WEAPON","TYPE","NOTES"].map(h=><div key={h} style={{padding:"6px 12px",fontSize:10,letterSpacing:2,color:C.dimmer,borderRight:`1px solid ${C.border}`}}>{h}</div>)}
                </div>
                {filtered.map((w,wi)=>(
                  <div key={wi} style={{display:"grid",gridTemplateColumns:"1fr 90px 1fr",borderBottom:wi<filtered.length-1?`1px solid #141810`:"none",background:wi%2===0?"#0a0c08":"#0d100b"}} onMouseEnter={e=>e.currentTarget.style.background=`${tier.color}08`} onMouseLeave={e=>e.currentTarget.style.background=wi%2===0?"#0a0c08":"#0d100b"}>
                    <div style={{padding:"9px 12px",fontSize:13,color:C.textBright,fontWeight:600,borderRight:`1px solid #141810`,display:"flex",alignItems:"center",gap:5}}><span style={{width:3,height:3,background:tier.color,display:"inline-block",flexShrink:0}}/>{w.name}</div>
                    <div style={{padding:"9px 12px",fontSize:12,color:C.textDim,borderRight:`1px solid #141810`,display:"flex",alignItems:"center"}}>{w.type}</div>
                    <div style={{padding:"9px 12px",fontSize:12,color:C.textDim,lineHeight:1.5,display:"flex",alignItems:"center"}}>{w.note}</div>
                  </div>
                ))}
              </div>
            </div>);
          })}
          <div style={{marginTop:8}}>
            <div style={{fontSize:11,letterSpacing:3,color:C.dim,marginBottom:10}}>AMMO TYPES</div>
            <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(200px,1fr))",gap:8}}>
              {[{type:"Light",col:C.green,desc:"Common, most weapons. Easy to farm."},{type:"Heavy",col:C.orange,desc:"Higher damage weapons. Scarcer in loot."},{type:"Volt",col:C.cyan,desc:"Energy ammo. Strong vs shields specifically."},{type:"MIPS",col:C.purple,desc:"Exotic alien hybrid. Rare, unusual weapon behavior."}].map((a,i)=>(
                <div key={i} style={{background:C.panel,border:`1px solid ${a.col}33`,borderLeft:`3px solid ${a.col}`,padding:"10px 12px"}}>
                  <div style={{fontSize:12,color:a.col,fontWeight:700,marginBottom:4}}>{a.type}</div>
                  <div style={{fontSize:11,color:C.textDim,lineHeight:1.5}}>{a.desc}</div>
                </div>
              ))}
            </div>
          </div>
        </>)}
        <div style={{marginTop:22,borderTop:`1px solid ${C.border}`,paddingTop:10,fontSize:10,color:C.dimmer,letterSpacing:2,textAlign:"center"}}>MARATHON · BUNGIE · MAR 5 2026 · EXTRACT ALIVE · DISCIPLINE BEATS GREED · SEASON 1</div>
      </div>
    </div>
  );
}
